<?php
// This file is automatically generated file

return array (
  'DEV_ENVIRONMENT' => 'development',
  'database' => 
  array (
    'tests' => 
    array (
      'hostname' => 'localhost',
      'database' => 'ci4_test',
      'username' => 'root',
      'password' => '',
      'DBDriver' => 'MySQLi',
      'port' => '3306',
    ),
  ),
);
