<?php
/**
 * This file is automatically generated at 2023/06/13 [ 10:26:40 AM ] 
 *
 */

return array (
  'DEV_ENVIRONMENT' => 'development',
  'app' => 
  array (
    'baseURL' => 'http://localhost:8000/',
  ),
  'database' => 
  array (
    'default' => 
    array (
      'hostname' => 'localhost',
      'database' => 'ci4',
      'username' => 'root',
      'password' => 'root',
      'DBDriver' => 'MySQLi',
      'DBPrefix' => '',
      'port' => '3306',
    ),
    'tests' => 
    array (
      'hostname' => 'localhost',
      'database' => 'ci4_test',
      'username' => 'root',
      'password' => '',
      'DBDriver' => 'MySQLi',
      'port' => '3306',
    ),
  ),
);
