<?php

// Read the .env file
$envContent = file_get_contents('../.env');
$conf = fopen("./'config.php'", "w") or die("Unable to open config file!");

$lines = explode("\n", $envContent);
$configArray = [];

foreach ($lines as $line) {
    // Ignore empty lines and comments
    if (empty($line) || strpos($line, '#') === 0) {
        continue;
    }

    // Split the line into key and value
    $parts = explode('=', $line, 2); 
    // Remove whitespace and quotes from the key and value
    $key = trim($parts[0] ?? '');
    $value = trim(trim($parts[1] ?? '', '\'"'));
    if(empty($key)) continue;

    // Create nested array structure for keys containing dots
    $keys = explode('.', $key);

    // Set the value in the nested array
    $nestedConfigReference = &$configArray;

    foreach ($keys as $nestedKey) {
        if (!isset($nestedConfigReference[$nestedKey])) {
            $nestedConfigReference[$nestedKey] = [];
        }

        $nestedConfigReference = &$nestedConfigReference[$nestedKey];
    }

    $nestedConfigReference = $value;
}

// Generate the config.php file content
$configContent = '<?php
// This file is automatically generated file' 
. PHP_EOL . PHP_EOL;
$configContent .= 'return ' . var_export($configArray, true) . ';' . PHP_EOL;

// Write the config.php file
fwrite($conf, $configContent);
fclose($conf);